# docker-compose.yml para la aplicación

version: "3"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root # USUARIO
      MYSQL_PASSWORD: password # CONTRASEÑA
      MYSQL_DATABASE: tfg_database # NOMBRE BASE DE DATOS
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tfg_database
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
