# docker-compose.yml para la aplicación

version: "3"

services:
  client: # Nombre del contenedor
    container_name: clientcontainer
    build: ./client # Ruta donde se encuentra nuestro Dockerfile
    image: client:v1
    ports:
      - 3001:3000 # Puerto nuestra máquina : Puerto Node.js dentro de Docker
    expose:
      - 3000
    links: # Utiliza el servicio de server para que se puedan comunicar entre los dos
      - server
    depends_on: # Se creara antes el contenedor de server que client
      - server
    restart: on-failure
    networks:
      - tfg-juego-educativo
  server: # Nombre del contenedor
    container_name: servercontainer
    build: 
      context: ./server # Ruta donde se encuentra nuestro Dockerfile
      dockerfile: Dockerfile
    image: server:v1
    ports:
      - 3000:3000 # Puerto nuestra máquina : Puerto Node.js dentro de Docker
    expose:
      - 3000
    volumes: 
      - ./server:/server
      - '/server/node_modules'
    env_file: ./server/.env
    environment:
      NODE_ENV: development
      SERVERIP: server
      PORT: 3000
      DB_HOST: mysql_server
      DB_PORT: 3306
      DB_USER: 'root'
      DB_PASSWORD: 'password'
      DB_DATABASE: tfg_database
      SECRET_KEY: 55cbd476502517479974ecef9a5d8d0d6e0beb71111e30585d2315eaafb97b78
      VERIFICACION: http://localhost:8080/app/verificacion
      CLIENT_DOMAIN: http://localhost:3000
      REDIRECT: http://localhost:3000/sign-in
      EMAIL: marco.gomez@alumnos.uneatlantico.es
      PASS_EMAIL: apxbkmwqsteyyosv
      SERVICE_TAGS: dev
      SERVICE_NAME: server
    stdin_open: true
    tty: true
    depends_on: # Se creara antes el contenedor de db que server
      - mysql_server
    restart: on-failure
    networks:
      - tfg-juego-educativo
  mysql_server:
    image: mysql:5.7
    container_name: mysqlcontainer
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tfg_database
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_server
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - tfg-juego-educativo
networks:
  tfg-juego-educativo:
    driver: bridge